### ISSUE TITLE
Issue with RIGHT SINGLE QUOTATION MARK (') character decoding

### ISSUE THREAD

**Issue by NehalH** [NehalH/Raisin#2]
Cannot decode RIGHT SINGLE QUOTATION MARK, displays '\xe2\x80\x99s' instead.

**Comment by Harshal662** [comment]
can you tell me on which line the error is

**Comment by NehalH** [comment]
This is a logic error, therefore I am yet to find the exact line causing the issue.
What happens is, the program reads from the file and encodes perfectly. But while decoding, it simply is unable to decode the 'single quotation' symbol (and also escape characters like \n).

I assume the issue probably lies in the functions participating in decoding (unpack(), read_from_raisin_file(), write_to_file() )

Thank you for reaching out and feel free to enquire more about the issue.

**Comment by NehalH** [comment]
Fixed.
Manually replaced right and left apostrophes with placeholders,
accommodated for escape sequences using .decode('unicode_escape')
replaced placeholders with actual characters.
NOTE: This is just a temporary fix.
